export const GET_BOOKS = 'GET_BOOKS';
export const EDIT_BOOK = 'EDIT_BOOK';
export const GET_AUTHORS = 'GET_AUTHORS';
export const FILTER_BY_AUTHOR = 'FILTER_BY_AUTHOR';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const GET_WISH_LIST = 'GET_WISH_LIST';